---
name: "Amazon Inbox to Archiv"
schedule: "every 24 hours"
action: "imap_mv"
# disabled: true
args:
  - mail_account: "mahillmannde-0001"
  - search:
    - field: "or"
      value:
      - field: "from"
        value: "versandbestaetigung@amazon.de"
      - field: "from"
        value: "marketplace-messages@amazon.de"
      - field: "from"
        value: "aws-marketing-email-replies@amazon.com"
  - moveTo: "Inbox/Archiv/AWS"
