---
name: "DZone Inbox to Archiv"
schedule: "every 5 minutes"
action: "imap_mv"
disabled: true
args:
  - mail_account: "mahillmannde-0001"
  - search:
    - field: "older"
      value: "P10D"
    - field: "or"
      value:
      - field: "from"
        value: "mailer@dzone.com"
      - field: "from"
        value: "noreply@dzone.com"
      - field: "from"
        value: "privacy@dzone.com"
  - moveTo: "Inbox/Archiv/DZone"
