---
name: "M-Net Inbox to MNet"
schedule: "every 5 minutes"
action: "imap_mv"
args:
  - mail_account: "mahillmannde-0001"
  - search:
    - field: "from"
      value: "newsletter@mail.m-net.de"
  - moveTo: "Inbox/Archiv/m-net"
