---
name: "DZone Inbox to Archiv"
schedule: "every 5 minutes"
action: "imap_mv"
disabled: true
args:
  - mail_account: "mahillmannde-0001"
  - mail_from: "info@mailer.netflix.com"
  - moveTo: "Inbox/Archiv/Netflix"
