---
name: "DZone Inbox to Backup MNet"
schedule: "every 5 minutes"
action: "imap_backup"
disabled: true
args:
  - mail_account: "mahillmannde-0001"
  - search:
    - field: "older"
      value: "P10D"
    - field: "or"
      value:
      - field: "from"
        value: "mailer@dzone.com"
      - field: "from"
        value: "noreply@dzone.com"
      - field: "from"
        value: "privacy@dzone.com"
  - path: "Inbox/Archiv/DZone"
  - target_account: "marcel@ds918.local"
  - saveTo: "Inbox/DZone"
