---
name: "DZone Inbox to Backup MNet"
schedule: "every second"
action: "imap_backup"
# disabled: true
args:
  - mail_account: "mahillmannde-0001"
  - mail_from: "mailer@dzone.com"
  - mail_older: "P10D"
  - path: "Inbox/Archiv/DZone"
  - target_account: "marcel@ds918.local"
  - saveTo: "Inbox/DZone"
