---
name: "MVV Input to Backup MVV"
schedule: "@daily"
action: "imap_backup"
disabled: true
args:
  - mail_account: "mahillmannde-0001"
  - mail_from: "service-dialog@mailing.bahn.de"
  - mail_older: "P10D"
  - path: "Inbox/Archiv/MVV"
  - target_account: "marcel@ds918.local"
  - saveTo: "Inbox/MVV"
