---
name: "M-Net mark at seen"
schedule: "every 1 hours"
action: "seen"
disabled: true
args:
  - mail_account: "mahillmannde-0001"
  - path: "Inbox/Archiv/MVV"
  - mail_from: "service-dialog@mailing.bahn.de"
  - mail_older: "24h"
  - mail_unseen: true
